version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=ABPVNext_Identity
      - ABPVNext_DB=ABPVNext_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
